from __future__ import annotations

import argparse
import csv
import json
import sys
import threading
import time
from collections import deque
from pathlib import Path

WINDOW_NAME_CAPTURE = "Screen Template Matcher - Capture"
WINDOW_NAME_DASHBOARD = "Screen Template Matcher - Match Details"
DEFAULT_TEMPLATE_SWITCH_FRAMES = 3
DATASET_CROP_SIZE = 96
SUPPORTED_IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".bmp", ".webp"}
cv2 = None
mss = None
np = None
MATCH_METHOD = None
sd = None


def ensure_dependencies_loaded() -> None:
    global cv2, mss, np, MATCH_METHOD, sd
    if cv2 is not None and mss is not None and np is not None and MATCH_METHOD is not None:
        return

    try:
        import cv2 as _cv2
        import mss as _mss
        import numpy as _np
        try:
            import sounddevice as _sd
        except ModuleNotFoundError:
            _sd = None
    except ModuleNotFoundError as exc:
        raise RuntimeError(
            "missing dependency. Install requirements with: pip install -r requirements.txt"
        ) from exc

    cv2 = _cv2
    mss = _mss
    np = _np
    sd = _sd
    MATCH_METHOD = cv2.TM_CCOEFF_NORMED


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Capture a screen region and perform template matching with local tracking."
    )
    parser.add_argument("--template", help="Path to a single local template image.")
    parser.add_argument("--template-dir", help="Path to a directory containing multiple template images.")
    parser.add_argument(
        "--manifest",
        help="Optional template manifest JSON. Defaults to manifest.json inside --template-dir when present.",
    )
    parser.add_argument("--config", help="Optional JSON config generated by desktop_region_selector.py.")
    parser.add_argument("--left", type=int, help="Left coordinate of the capture region.")
    parser.add_argument("--top", type=int, help="Top coordinate of the capture region.")
    parser.add_argument("--region-width", type=int, help="Width of the capture region.")
    parser.add_argument("--region-height", type=int, help="Height of the capture region.")
    parser.add_argument("--fps", type=float, default=5.0, help="Capture frequency in frames per second. Default: 5.")
    parser.add_argument("--threshold", type=float, default=0.8, help="Similarity threshold used for hit labeling.")
    parser.add_argument(
        "--match-mode",
        choices=("color", "gray", "edge", "texture", "halo", "float", "combined"),
        default="gray",
        help="Default template matching mode. Default: gray.",
    )
    parser.add_argument(
        "--candidate-mask-mode",
        choices=("float", "halo", "intersection"),
        default="float",
        help="Base mask used to generate candidate regions. Default: float.",
    )
    parser.add_argument(
        "--use-halo-gate",
        dest="use_halo_gate",
        action="store_true",
        default=False,
        help="Require candidate boxes to retain some halo support before candidate matching.",
    )
    parser.add_argument(
        "--no-halo-gate",
        dest="use_halo_gate",
        action="store_false",
        help="Disable halo-based candidate gating.",
    )
    parser.add_argument(
        "--tracking-threshold",
        type=float,
        default=0.6,
        help="Minimum score to keep target lock during local tracking. Default: 0.6.",
    )
    parser.add_argument(
        "--reacquire-frames",
        type=int,
        default=5,
        help="How many low-score frames to tolerate before global re-search. Default: 5.",
    )
    parser.add_argument(
        "--search-padding",
        type=int,
        default=80,
        help="Padding around the last target position for local search. Default: 80.",
    )
    parser.add_argument(
        "--history-size",
        type=int,
        default=20,
        help="How many recent tracking points to retain. Default: 20.",
    )
    parser.add_argument(
        "--bite-window",
        type=int,
        default=6,
        help="Recent frame count used to judge a bite-like drop event. Default: 6.",
    )
    parser.add_argument(
        "--bite-drop-pixels",
        type=float,
        default=18.0,
        help="Minimum downward movement in pixels within the bite window. Default: 18.",
    )
    parser.add_argument(
        "--candidate-threshold",
        type=float,
        default=0.52,
        help="Default score required to accept a candidate-box template confirmation. Default: 0.52.",
    )
    parser.add_argument(
        "--candidate-min-area",
        type=int,
        default=36,
        help="Minimum connected-component area for float candidates. Default: 36.",
    )
    parser.add_argument(
        "--max-candidates",
        type=int,
        default=8,
        help="Maximum number of candidate boxes kept after ranking. Default: 8.",
    )
    parser.add_argument(
        "--sound-threshold",
        type=float,
        default=80.0,
        help="Volume threshold used by the live sound monitor. Default: 80.",
    )
    parser.add_argument(
        "--sound-notification-duration",
        type=float,
        default=2.0,
        help="How long the sound-trigger notification stays visible in preview windows. Default: 2 seconds.",
    )
    parser.add_argument(
        "--enable-sound-monitor",
        dest="enable_sound_monitor",
        action="store_true",
        default=True,
        help="Enable live sound monitoring for notification overlays. Enabled by default.",
    )
    parser.add_argument(
        "--no-sound-monitor",
        dest="enable_sound_monitor",
        action="store_false",
        help="Disable live sound monitoring.",
    )
    parser.add_argument(
        "--save-candidate-dataset",
        dest="save_candidate_dataset",
        action="store_true",
        default=False,
        help="Save each filtered candidate crop into ./data/float or ./data/non_float for training.",
    )
    parser.add_argument(
        "--no-save-candidate-dataset",
        dest="save_candidate_dataset",
        action="store_false",
        help="Disable candidate dataset export.",
    )
    parser.add_argument(
        "--dataset-dir",
        default="data",
        help="Root directory used by candidate dataset export. Default: ./data",
    )
    parser.add_argument(
        "--show-preview",
        dest="show_preview",
        action="store_true",
        default=True,
        help="Show live preview windows. Enabled by default.",
    )
    parser.add_argument(
        "--no-preview",
        dest="show_preview",
        action="store_false",
        help="Disable preview windows and print similarity only.",
    )
    parser.add_argument(
        "--replay-dir",
        help="Optional directory of image frames to evaluate offline instead of live screen capture.",
    )
    parser.add_argument(
        "--replay-output",
        help="Optional JSON or CSV output path for offline replay results.",
    )
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    if not args.template and not args.template_dir:
        raise ValueError("either --template or --template-dir must be provided")
    if args.fps <= 0:
        raise ValueError("fps must be greater than 0")
    if not 0.0 <= args.threshold <= 1.0:
        raise ValueError("threshold must be between 0.0 and 1.0")
    if not 0.0 <= args.tracking_threshold <= 1.0:
        raise ValueError("tracking-threshold must be between 0.0 and 1.0")
    if args.reacquire_frames <= 0:
        raise ValueError("reacquire-frames must be greater than 0")
    if args.search_padding < 0:
        raise ValueError("search-padding must be 0 or greater")
    if args.history_size < 2:
        raise ValueError("history-size must be at least 2")
    if args.bite_window < 2:
        raise ValueError("bite-window must be at least 2")
    if args.bite_drop_pixels <= 0:
        raise ValueError("bite-drop-pixels must be greater than 0")
    if not 0.0 <= args.candidate_threshold <= 1.0:
        raise ValueError("candidate-threshold must be between 0.0 and 1.0")
    if args.candidate_min_area <= 0:
        raise ValueError("candidate-min-area must be greater than 0")
    if args.max_candidates <= 0:
        raise ValueError("max-candidates must be greater than 0")
    if args.sound_threshold <= 0:
        raise ValueError("sound-threshold must be greater than 0")
    if args.sound_notification_duration <= 0:
        raise ValueError("sound-notification-duration must be greater than 0")
    if not str(args.dataset_dir).strip():
        raise ValueError("dataset-dir must not be empty")
    if args.left is None and args.top is not None:
        raise ValueError("left and top must be provided together")
    if args.top is None and args.left is not None:
        raise ValueError("left and top must be provided together")
    if args.region_width is not None and args.region_width <= 0:
        raise ValueError("region-width must be greater than 0")
    if args.region_height is not None and args.region_height <= 0:
        raise ValueError("region-height must be greater than 0")
    if args.replay_output and Path(args.replay_output).suffix.lower() not in (".json", ".csv"):
        raise ValueError("replay-output must end with .json or .csv")
    if args.replay_dir:
        replay_path = Path(args.replay_dir).expanduser().resolve()
        if not replay_path.exists() or not replay_path.is_dir():
            raise ValueError(f"replay directory not found: {replay_path}")
    elif args.region_width is None or args.region_height is None:
        raise ValueError("region width and height must be provided directly or via --config")


def ensure_directory_exists(path: Path, label: str) -> Path:
    if path.exists():
        if not path.is_dir():
            raise ValueError(f"{label} must be a directory: {path}")
        return path
    path.mkdir(parents=True, exist_ok=True)
    print(f"Created missing {label}: {path}", flush=True)
    return path


def prepare_path_arguments(args: argparse.Namespace) -> argparse.Namespace:
    if args.template_dir:
        args.template_dir = str(
            ensure_directory_exists(Path(args.template_dir).expanduser().resolve(), "template directory")
        )
    if args.replay_dir:
        args.replay_dir = str(
            ensure_directory_exists(Path(args.replay_dir).expanduser().resolve(), "replay directory")
        )
    if args.manifest:
        manifest_path = Path(args.manifest).expanduser().resolve()
        ensure_directory_exists(manifest_path.parent, "manifest parent directory")
        args.manifest = str(manifest_path)
    if args.replay_output:
        replay_output = Path(args.replay_output).expanduser().resolve()
        ensure_directory_exists(replay_output.parent, "replay output parent directory")
        args.replay_output = str(replay_output)
    if args.dataset_dir:
        dataset_dir = Path(args.dataset_dir).expanduser().resolve()
        if args.save_candidate_dataset:
            ensure_directory_exists(dataset_dir, "dataset directory")
        args.dataset_dir = str(dataset_dir)
    return args


def preprocess_gray(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    gray = cv2.GaussianBlur(gray, (3, 3), 0)
    return cv2.equalizeHist(gray)


def preprocess_edges(image):
    gray = preprocess_gray(image)
    return cv2.Canny(gray, 50, 150)


def preprocess_texture(image):
    gray = preprocess_gray(image)
    blur = cv2.GaussianBlur(gray, (0, 0), 3.0)
    high_pass = cv2.addWeighted(gray, 1.8, blur, -0.8, 0)
    grad_x = cv2.Sobel(high_pass, cv2.CV_32F, 1, 0, ksize=3)
    grad_y = cv2.Sobel(high_pass, cv2.CV_32F, 0, 1, ksize=3)
    magnitude = cv2.magnitude(grad_x, grad_y)
    magnitude = cv2.normalize(magnitude, None, 0, 255, cv2.NORM_MINMAX)
    magnitude = magnitude.astype(np.uint8)
    _, binary = cv2.threshold(magnitude, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    kernel = np.ones((3, 3), np.uint8)
    opened = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel, iterations=1)
    return cv2.dilate(opened, kernel, iterations=1)


def preprocess_halo(image):
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    lower_yellow = np.array([18, 50, 130], dtype=np.uint8)
    upper_yellow = np.array([45, 255, 255], dtype=np.uint8)
    mask = cv2.inRange(hsv, lower_yellow, upper_yellow)

    lab = cv2.cvtColor(image, cv2.COLOR_BGR2LAB)
    l_channel, _a_channel, b_channel = cv2.split(lab)
    bright_mask = cv2.inRange(l_channel, 140, 255)
    warm_mask = cv2.inRange(b_channel, 140, 255)
    mask = cv2.bitwise_or(mask, cv2.bitwise_and(bright_mask, warm_mask))

    kernel_small = np.ones((3, 3), np.uint8)
    kernel_large = np.ones((5, 5), np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel_small, iterations=1)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel_large, iterations=2)
    return cv2.dilate(mask, kernel_small, iterations=1)


def preprocess_float_mask(image):
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    lab = cv2.cvtColor(image, cv2.COLOR_BGR2LAB)

    h_channel, s_channel, v_channel = cv2.split(hsv)
    l_channel, _a_channel, b_channel = cv2.split(lab)

    not_water = cv2.inRange(h_channel, 0, 179)
    blue_water = cv2.inRange(h_channel, 85, 135)
    not_water = cv2.bitwise_and(not_water, cv2.bitwise_not(blue_water))

    saturated = cv2.inRange(s_channel, 35, 255)
    bright = cv2.inRange(v_channel, 95, 255)
    warm_or_neutral = cv2.inRange(b_channel, 118, 255)
    light_outline = cv2.inRange(l_channel, 140, 255)

    edge = preprocess_edges(image)
    texture = preprocess_texture(image)

    color_candidate = cv2.bitwise_and(not_water, saturated)
    color_candidate = cv2.bitwise_and(color_candidate, bright)
    outline_candidate = cv2.bitwise_and(light_outline, cv2.bitwise_or(edge, texture))
    warm_candidate = cv2.bitwise_and(warm_or_neutral, cv2.bitwise_or(edge, texture))

    mask = cv2.bitwise_or(color_candidate, outline_candidate)
    mask = cv2.bitwise_or(mask, warm_candidate)

    kernel_small = np.ones((3, 3), np.uint8)
    kernel_large = np.ones((5, 5), np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel_small, iterations=1)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel_large, iterations=2)
    return cv2.dilate(mask, kernel_small, iterations=1)


def prepare_variant(image, mode: str):
    if mode == "color":
        return image
    if mode == "gray":
        return preprocess_gray(image)
    if mode == "edge":
        return preprocess_edges(image)
    if mode == "combined":
        gray = preprocess_gray(image)
        edge = preprocess_edges(image)
        return cv2.addWeighted(gray, 0.7, edge, 0.3, 0)
    if mode == "texture":
        return preprocess_texture(image)
    if mode == "halo":
        return preprocess_halo(image)
    if mode == "float":
        return preprocess_float_mask(image)
    raise ValueError(f"unsupported variant mode: {mode}")

def load_config(config_path: Path) -> dict:
    if not config_path.exists():
        raise FileNotFoundError(f"config file not found: {config_path}")
    try:
        return json.loads(config_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"failed to parse config JSON: {config_path}") from exc


def load_image_file(image_path: Path):
    if not image_path.exists():
        raise FileNotFoundError(f"image not found: {image_path}")
    if not image_path.is_file():
        raise ValueError(f"image path is not a file: {image_path}")

    image = cv2.imread(str(image_path), cv2.IMREAD_COLOR)
    if image is None:
        raise ValueError(f"failed to load image: {image_path}")
    return image


def normalize_manifest_entries(payload) -> list[dict]:
    if isinstance(payload, list):
        return payload
    if isinstance(payload, dict) and isinstance(payload.get("templates"), list):
        return payload["templates"]
    raise ValueError("template manifest must be a list or contain a 'templates' list")


def discover_template_files(template_dir: Path) -> list[Path]:
    return sorted(
        path for path in template_dir.iterdir() if path.is_file() and path.suffix.lower() in SUPPORTED_IMAGE_SUFFIXES
    )


def load_templates(args: argparse.Namespace) -> tuple[list[dict], str]:
    template_entries = []
    source_note = ""

    if args.template_dir:
        template_dir = Path(args.template_dir).expanduser().resolve()
        if not template_dir.exists() or not template_dir.is_dir():
            raise ValueError(f"template directory not found: {template_dir}")

        if args.template:
            print("Template directory provided; ignoring --template and using directory templates.", flush=True)

        manifest_path = None
        if args.manifest:
            manifest_path = Path(args.manifest).expanduser().resolve()
        else:
            candidate_manifest = template_dir / "manifest.json"
            if candidate_manifest.exists():
                manifest_path = candidate_manifest

        manifest_entries: list[dict] = []
        if manifest_path is not None:
            payload = load_config(manifest_path)
            manifest_entries = normalize_manifest_entries(payload)

        if manifest_entries:
            for index, entry in enumerate(manifest_entries):
                if not isinstance(entry, dict):
                    raise ValueError("every template manifest entry must be an object")
                raw_path = entry.get("path")
                if not raw_path:
                    raise ValueError(f"template manifest entry #{index + 1} is missing 'path'")
                template_path = (manifest_path.parent / raw_path).resolve()
                template_id = entry.get("id") or template_path.stem
                category = entry.get("category", "float")
                match_mode = entry.get("match_mode", args.match_mode)
                candidate_threshold = float(entry.get("candidate_threshold", args.candidate_threshold))
                tracking_threshold = float(entry.get("tracking_threshold", args.tracking_threshold))
                image = load_image_file(template_path)
                template_entries.append(
                    {
                        "id": str(template_id),
                        "path": template_path,
                        "category": str(category),
                        "match_mode": str(match_mode),
                        "candidate_threshold": candidate_threshold,
                        "tracking_threshold": tracking_threshold,
                        "image": image,
                        "width": int(image.shape[1]),
                        "height": int(image.shape[0]),
                    }
                )
            source_note = f"manifest={manifest_path}"
        else:
            for template_path in discover_template_files(template_dir):
                image = load_image_file(template_path)
                template_entries.append(
                    {
                        "id": template_path.stem,
                        "path": template_path,
                        "category": "float",
                        "match_mode": args.match_mode,
                        "candidate_threshold": args.candidate_threshold,
                        "tracking_threshold": args.tracking_threshold,
                        "image": image,
                        "width": int(image.shape[1]),
                        "height": int(image.shape[0]),
                    }
                )
            source_note = f"directory={template_dir}"
    else:
        template_path = Path(args.template).expanduser().resolve()
        image = load_image_file(template_path)
        template_entries.append(
            {
                "id": template_path.stem,
                "path": template_path,
                "category": "float",
                "match_mode": args.match_mode,
                "candidate_threshold": args.candidate_threshold,
                "tracking_threshold": args.tracking_threshold,
                "image": image,
                "width": int(image.shape[1]),
                "height": int(image.shape[0]),
            }
        )
        source_note = f"template={template_path}"

    if not template_entries:
        raise ValueError("no templates were loaded")

    for entry in template_entries:
        if entry["match_mode"] not in ("color", "gray", "edge", "texture", "halo", "float", "combined"):
            raise ValueError(f"unsupported template match_mode for {entry['id']}: {entry['match_mode']}")
        if not 0.0 <= entry["candidate_threshold"] <= 1.0:
            raise ValueError(f"candidate_threshold for {entry['id']} must be between 0.0 and 1.0")
        if not 0.0 <= entry["tracking_threshold"] <= 1.0:
            raise ValueError(f"tracking_threshold for {entry['id']} must be between 0.0 and 1.0")

    return template_entries, source_note


def describe_template_entries(template_entries: list[dict]) -> str:
    parts = []
    for entry in template_entries:
        parts.append(
            f"{entry['id']}[{entry['match_mode']} c={entry['candidate_threshold']:.2f} t={entry['tracking_threshold']:.2f}]"
        )
    return ", ".join(parts)


def get_primary_monitor(sct: mss.mss) -> dict:
    if len(sct.monitors) < 2:
        raise RuntimeError("no primary monitor information available")
    return sct.monitors[1]


def resolve_region(args: argparse.Namespace, monitor: dict) -> dict:
    if args.region_width is None or args.region_height is None:
        raise ValueError("region width and height must be provided directly or via --config")

    if args.left is not None or args.top is not None:
        if args.left is None or args.top is None:
            raise ValueError("left and top must be provided together")
        return {
            "left": args.left,
            "top": args.top,
            "width": args.region_width,
            "height": args.region_height,
        }

    monitor_left = monitor["left"]
    monitor_top = monitor["top"]
    monitor_width = monitor["width"]
    monitor_height = monitor["height"]
    if args.region_width > monitor_width or args.region_height > monitor_height:
        raise ValueError("capture region cannot be larger than the primary monitor")

    left = monitor_left + (monitor_width - args.region_width) // 2
    top = monitor_top + (monitor_height - args.region_height) // 2
    return {"left": left, "top": top, "width": args.region_width, "height": args.region_height}


def apply_config_defaults(args: argparse.Namespace) -> argparse.Namespace:
    if not args.config:
        return args

    config_path = Path(args.config).expanduser().resolve()
    config = load_config(config_path)
    capture_region = config.get("capture_region", {})
    matcher_defaults = config.get("matcher_defaults", {})

    if args.left is None:
        args.left = capture_region.get("left")
    if args.top is None:
        args.top = capture_region.get("top")
    if args.region_width is None:
        args.region_width = capture_region.get("width")
    if args.region_height is None:
        args.region_height = capture_region.get("height")
    if args.fps == 5.0 and "fps" in matcher_defaults:
        args.fps = matcher_defaults["fps"]
    if args.threshold == 0.8 and "threshold" in matcher_defaults:
        args.threshold = matcher_defaults["threshold"]
    if args.max_candidates == 8 and "max_candidates" in matcher_defaults:
        args.max_candidates = matcher_defaults["max_candidates"]
    if args.sound_threshold == 80.0 and "sound_threshold" in matcher_defaults:
        args.sound_threshold = matcher_defaults["sound_threshold"]
    if args.sound_notification_duration == 2.0 and "sound_notification_duration" in matcher_defaults:
        args.sound_notification_duration = matcher_defaults["sound_notification_duration"]
    if args.dataset_dir == "data" and "dataset_dir" in matcher_defaults:
        args.dataset_dir = matcher_defaults["dataset_dir"]
    if not args.save_candidate_dataset and matcher_defaults.get("save_candidate_dataset") is True:
        args.save_candidate_dataset = True
    if args.enable_sound_monitor and matcher_defaults.get("enable_sound_monitor") is False:
        args.enable_sound_monitor = False
    if args.show_preview and matcher_defaults.get("show_preview") is False:
        args.show_preview = False

    return args


def validate_region(region: dict, monitor: dict) -> None:
    if region["width"] <= 0 or region["height"] <= 0:
        raise ValueError("capture region dimensions must be positive")
    if region["left"] < monitor["left"] or region["top"] < monitor["top"]:
        raise ValueError("capture region cannot start outside the primary monitor")
    if region["left"] + region["width"] > monitor["left"] + monitor["width"]:
        raise ValueError("capture region exceeds the primary monitor width")
    if region["top"] + region["height"] > monitor["top"] + monitor["height"]:
        raise ValueError("capture region exceeds the primary monitor height")


def ensure_templates_fit(region: dict, template_entries: list[dict]) -> None:
    for entry in template_entries:
        if entry["width"] > region["width"] or entry["height"] > region["height"]:
            raise ValueError(
                f"template image must not be larger than the capture region: {entry['path']}"
            )


def capture_region(sct: mss.mss, region: dict):
    raw = np.array(sct.grab(region))
    return cv2.cvtColor(raw, cv2.COLOR_BGRA2BGR)


def run_single_match(frame_variant, template_variant) -> tuple[float, tuple[int, int], np.ndarray]:
    result = cv2.matchTemplate(frame_variant, template_variant, MATCH_METHOD)
    _, max_val, _, max_loc = cv2.minMaxLoc(result)
    return float(max_val), max_loc, result


def match_template(frame, template, match_mode: str) -> dict:
    if match_mode == "combined":
        gray_score, gray_top_left, gray_result = run_single_match(
            prepare_variant(frame, "gray"),
            prepare_variant(template, "gray"),
        )
        edge_score, edge_top_left, _edge_result = run_single_match(
            prepare_variant(frame, "edge"),
            prepare_variant(template, "edge"),
        )
        fused_score = gray_score * 0.7 + edge_score * 0.3
        fused_top_left = gray_top_left if gray_score >= edge_score else edge_top_left
        return {
            "best_mode": "combined",
            "score": fused_score,
            "top_left": fused_top_left,
            "result_map": gray_result,
            "scores": {
                "gray": gray_score,
                "edge": edge_score,
                "combined": fused_score,
            },
        }

    matches = {}
    for mode in ("color", "gray", "edge", "texture", "halo", "float"):
        if match_mode == mode:
            score, top_left, result = run_single_match(prepare_variant(frame, mode), prepare_variant(template, mode))
            matches[mode] = {"score": score, "top_left": top_left, "result_map": result}

    if not matches:
        raise ValueError(f"unsupported match mode: {match_mode}")

    best_mode = max(matches.items(), key=lambda item: item[1]["score"])[0]
    best = matches[best_mode]
    return {
        "best_mode": best_mode,
        "score": best["score"],
        "top_left": best["top_left"],
        "result_map": best["result_map"],
        "scores": {name: details["score"] for name, details in matches.items()},
    }

def clip_search_region(region: dict, frame_shape, template_shape, padding: int) -> dict:
    frame_height, frame_width = frame_shape[:2]
    template_height, template_width = template_shape[:2]
    left = max(0, region["left"] - padding)
    top = max(0, region["top"] - padding)
    right = min(frame_width, region["left"] + region["width"] + padding)
    bottom = min(frame_height, region["top"] + region["height"] + padding)

    if right - left < template_width:
        right = min(frame_width, left + template_width)
        left = max(0, right - template_width)
    if bottom - top < template_height:
        bottom = min(frame_height, top + template_height)
        top = max(0, bottom - template_height)

    return {"left": left, "top": top, "width": right - left, "height": bottom - top}


def crop_frame(frame, search_region: dict):
    left = search_region["left"]
    top = search_region["top"]
    right = left + search_region["width"]
    bottom = top + search_region["height"]
    return frame[top:bottom, left:right]


def absolute_rect(top_left: tuple[int, int], template_shape, offset: tuple[int, int]) -> dict:
    template_height, template_width = template_shape[:2]
    left = top_left[0] + offset[0]
    top = top_left[1] + offset[1]
    return {
        "left": left,
        "top": top,
        "width": template_width,
        "height": template_height,
        "right": left + template_width,
        "bottom": top + template_height,
        "center_x": left + template_width / 2.0,
        "center_y": top + template_height / 2.0,
    }


def build_candidate_mask(float_mask, halo_mask, mode: str):
    if mode == "float":
        return float_mask
    if mode == "halo":
        return halo_mask
    if mode == "intersection":
        return cv2.bitwise_and(float_mask, halo_mask)
    raise ValueError(f"unsupported candidate-mask-mode: {mode}")


def get_template_pool(
    template_entries: list[dict],
    active_template_id: str | None,
    allow_template_switch: bool,
) -> tuple[list[dict], dict | None]:
    active_entry = next((entry for entry in template_entries if entry["id"] == active_template_id), None)
    if active_entry is not None and not allow_template_switch:
        return [active_entry], active_entry
    return template_entries, active_entry


def build_candidate_regions(
    mask,
    frame,
    halo_mask,
    template_entries: list[dict],
    tracked_rect: dict | None,
    search_padding: int,
    candidate_min_area: int,
    max_candidates: int,
    use_halo_gate: bool,
) -> tuple[list[dict], dict]:
    frame_height, frame_width = frame.shape[:2]
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    gray_frame = preprocess_gray(frame)

    widths = [entry["width"] for entry in template_entries]
    heights = [entry["height"] for entry in template_entries]
    target_width = float(sum(widths) / max(1, len(widths)))
    target_height = float(sum(heights) / max(1, len(heights)))

    kept = []
    debug = {
        "raw_candidates": 0,
        "post_size_candidates": 0,
        "gated_candidates": 0,
        "rejected_by_aspect": 0,
        "rejected_by_halo": 0,
    }

    for contour in contours:
        x, y, w, h = cv2.boundingRect(contour)
        debug["raw_candidates"] += 1
        area = w * h
        if area < candidate_min_area:
            continue
        if w > frame_width * 0.4 or h > frame_height * 0.4:
            continue

        aspect_ratio = w / max(h, 1)
        if aspect_ratio < 0.2 or aspect_ratio > 4.5:
            debug["rejected_by_aspect"] += 1
            continue

        expanded_left = max(0, x - max(search_padding // 2, int(target_width // 3)))
        expanded_top = max(0, y - max(search_padding // 2, int(target_height // 3)))
        expanded_right = min(frame_width, x + w + max(search_padding // 2, int(target_width // 3)))
        expanded_bottom = min(frame_height, y + h + max(search_padding // 2, int(target_height // 3)))

        crop_width = expanded_right - expanded_left
        crop_height = expanded_bottom - expanded_top
        if crop_width <= 0 or crop_height <= 0:
            continue

        candidate_gray = gray_frame[expanded_top:expanded_bottom, expanded_left:expanded_right]
        candidate_halo = halo_mask[expanded_top:expanded_bottom, expanded_left:expanded_right]
        brightness = float(candidate_gray.mean()) if candidate_gray.size else 0.0
        halo_overlap = float((candidate_halo > 0).sum()) / float(candidate_halo.size) if candidate_halo.size else 0.0
        size_delta = abs(crop_width - target_width) + abs(crop_height - target_height)
        brightness_penalty = abs(brightness - 160.0)

        candidate = {
            "left": expanded_left,
            "top": expanded_top,
            "width": crop_width,
            "height": crop_height,
            "area": area,
            "aspect_ratio": aspect_ratio,
            "brightness": brightness,
            "halo_overlap": halo_overlap,
            "size_delta": size_delta,
        }

        if tracked_rect is not None:
            center_x = candidate["left"] + candidate["width"] / 2.0
            center_y = candidate["top"] + candidate["height"] / 2.0
            candidate["priority"] = abs(center_x - tracked_rect["center_x"]) + abs(center_y - tracked_rect["center_y"])
        else:
            candidate["priority"] = 0.0

        candidate["brightness_penalty"] = brightness_penalty
        debug["post_size_candidates"] += 1

        if use_halo_gate and halo_overlap <= 0.0:
            debug["rejected_by_halo"] += 1
            continue

        kept.append(candidate)

    if tracked_rect is not None:
        kept.sort(key=lambda item: (item["priority"], item["size_delta"], -item["halo_overlap"], item["brightness_penalty"], -item["area"]))
    else:
        kept.sort(key=lambda item: (item["size_delta"], -item["halo_overlap"], item["brightness_penalty"], -item["area"]))

    kept = kept[:max_candidates]
    debug["gated_candidates"] = len(kept)
    return kept, debug


def enrich_match_result(match_info: dict, template_entry: dict, search_region: dict | None, source: str) -> dict:
    match_info["template_id"] = template_entry["id"]
    match_info["template_path"] = str(template_entry["path"])
    match_info["template_category"] = template_entry["category"]
    match_info["template_image"] = template_entry["image"]
    match_info["candidate_threshold"] = template_entry["candidate_threshold"]
    match_info["tracking_threshold"] = template_entry["tracking_threshold"]
    match_info["search_source"] = source
    match_info["search_region"] = search_region
    return match_info


def match_templates_in_region(
    frame,
    template_entries: list[dict],
    fallback_match_mode: str,
    search_region: dict | None,
    source: str,
) -> dict | None:
    best_match = None
    template_scores = []
    for template_entry in template_entries:
        template = template_entry["image"]
        if frame.shape[1] < template.shape[1] or frame.shape[0] < template.shape[0]:
            continue
        match_info = match_template(frame, template, template_entry.get("match_mode", fallback_match_mode))
        template_scores.append(
            {
                "template_id": template_entry["id"],
                "score": float(match_info["score"]),
                "best_mode": match_info["best_mode"],
            }
        )
        offset = (search_region["left"], search_region["top"]) if search_region is not None else (0, 0)
        match_info["target_rect"] = absolute_rect(match_info["top_left"], template.shape, offset)
        enrich_match_result(match_info, template_entry, search_region, source)
        if best_match is None or match_info["score"] > best_match["score"]:
            best_match = match_info
    if best_match is not None:
        best_match["template_scores"] = sorted(template_scores, key=lambda item: item["score"], reverse=True)
    return best_match


def match_in_candidates(
    frame,
    template_entries: list[dict],
    fallback_match_mode: str,
    candidates: list[dict],
) -> tuple[dict | None, list[dict]]:
    best_match = None
    candidate_evaluations = []
    for index, candidate in enumerate(candidates):
        candidate_frame = crop_frame(frame, candidate)
        match_info = match_templates_in_region(
            frame=candidate_frame,
            template_entries=template_entries,
            fallback_match_mode=fallback_match_mode,
            search_region=candidate,
            source="candidate",
        )
        evaluation = {
            "candidate_index": index,
            "candidate_box": dict(candidate),
            "score": 0.0,
            "threshold": 0.0,
            "accepted": False,
            "template_id": None,
            "best_mode": None,
        }
        if match_info is None:
            candidate_evaluations.append(evaluation)
            continue
        match_info["candidate_box"] = candidate
        evaluation.update(
            {
                "score": float(match_info["score"]),
                "threshold": float(match_info["candidate_threshold"]),
                "accepted": bool(match_info["score"] >= match_info["candidate_threshold"]),
                "template_id": match_info["template_id"],
                "best_mode": match_info["best_mode"],
            }
        )
        candidate_evaluations.append(evaluation)
        if best_match is None or match_info["score"] > best_match["score"]:
            best_match = match_info
    if best_match is not None:
        best_match["candidate_evaluations"] = candidate_evaluations
    return best_match, candidate_evaluations


def build_step_result(
    match_info: dict,
    float_mask,
    halo_mask,
    candidate_boxes: list[dict],
    candidate_evaluations: list[dict],
    candidate_debug: dict,
    failure_reason: str | None,
    candidate_mask_mode: str,
    use_halo_gate: bool,
) -> dict:
    match_info["float_mask"] = float_mask
    match_info["halo_mask"] = halo_mask
    match_info["candidate_boxes"] = candidate_boxes
    match_info["candidate_evaluations"] = candidate_evaluations
    match_info["candidate_debug"] = candidate_debug
    match_info["failure_reason"] = failure_reason
    match_info["candidate_mask_mode"] = candidate_mask_mode
    match_info["halo_gate_enabled"] = use_halo_gate
    return match_info


def detect_target(
    frame,
    template_entries: list[dict],
    match_mode: str,
    tracked_rect: dict | None,
    search_padding: int,
    use_halo_gate: bool,
    candidate_mask_mode: str,
    candidate_min_area: int,
    max_candidates: int,
    active_template_id: str | None,
    allow_template_switch: bool,
) -> dict:
    float_mask = preprocess_float_mask(frame)
    halo_mask = preprocess_halo(frame)
    base_mask = build_candidate_mask(float_mask, halo_mask, candidate_mask_mode)
    template_pool, active_entry = get_template_pool(template_entries, active_template_id, allow_template_switch)
    candidate_boxes, candidate_debug = build_candidate_regions(
        mask=base_mask,
        frame=frame,
        halo_mask=halo_mask,
        template_entries=template_pool,
        tracked_rect=tracked_rect,
        search_padding=search_padding,
        candidate_min_area=candidate_min_area,
        max_candidates=max_candidates,
        use_halo_gate=use_halo_gate,
    )
    candidate_debug["mask_mode"] = candidate_mask_mode
    candidate_debug["halo_gate_enabled"] = use_halo_gate
    candidate_debug["active_template_locked"] = active_entry["id"] if active_entry is not None else None
    candidate_evaluations = []

    if candidate_boxes:
        candidate_match, candidate_evaluations = match_in_candidates(
            frame=frame,
            template_entries=template_pool,
            fallback_match_mode=match_mode,
            candidates=candidate_boxes,
        )
        candidate_debug["candidate_exportable"] = len(candidate_evaluations)
        candidate_debug["candidate_float_labels"] = sum(1 for item in candidate_evaluations if item["accepted"])
        if candidate_match is not None:
            candidate_debug["candidate_score"] = candidate_match["score"]
            candidate_debug["candidate_template_id"] = candidate_match["template_id"]
            if candidate_match["score"] >= candidate_match["candidate_threshold"]:
                candidate_debug["candidate_accepted"] = True
                return build_step_result(
                    candidate_match,
                    float_mask,
                    halo_mask,
                    candidate_boxes,
                    candidate_evaluations,
                    candidate_debug,
                    None,
                    candidate_mask_mode,
                    use_halo_gate,
                )
            candidate_failure = "candidate_score_too_low"
        else:
            candidate_failure = "candidate_match_failed"
    else:
        candidate_failure = "no_candidates"

    if tracked_rect is not None and template_pool:
        max_template_height = max(entry["height"] for entry in template_pool)
        max_template_width = max(entry["width"] for entry in template_pool)
        template_shape = (max_template_height, max_template_width, 3)
        local_region = clip_search_region(tracked_rect, frame.shape, template_shape, search_padding)
        local_frame = crop_frame(frame, local_region)
        local_match = match_templates_in_region(
            frame=local_frame,
            template_entries=template_pool,
            fallback_match_mode=match_mode,
            search_region=local_region,
            source="local",
        )
        if local_match is not None and local_match["score"] >= local_match["candidate_threshold"]:
            return build_step_result(
                local_match,
                float_mask,
                halo_mask,
                candidate_boxes,
                candidate_evaluations,
                candidate_debug,
                candidate_failure,
                candidate_mask_mode,
                use_halo_gate,
            )

    global_match = match_templates_in_region(
        frame=frame,
        template_entries=template_pool,
        fallback_match_mode=match_mode,
        search_region=None,
        source="global",
    )
    if global_match is None:
        raise RuntimeError("no template could be matched in the current frame")
    return build_step_result(
        global_match,
        float_mask,
        halo_mask,
        candidate_boxes,
        candidate_evaluations,
        candidate_debug,
        candidate_failure,
        candidate_mask_mode,
        use_halo_gate,
    )


def build_candidate_dataset_exporter(args: argparse.Namespace) -> dict:
    root_dir = Path(args.dataset_dir).expanduser().resolve()
    float_dir = root_dir / "float"
    non_float_dir = root_dir / "non_float"
    if args.save_candidate_dataset:
        ensure_directory_exists(root_dir, "dataset directory")
        ensure_directory_exists(float_dir, "float dataset directory")
        ensure_directory_exists(non_float_dir, "non-float dataset directory")
    return {
        "enabled": bool(args.save_candidate_dataset),
        "root_dir": root_dir,
        "float_dir": float_dir,
        "non_float_dir": non_float_dir,
        "counter": 0,
    }


def save_candidate_dataset_samples(frame, match_info: dict, dataset_exporter: dict, frame_index: int, source_label: str) -> None:
    if not dataset_exporter.get("enabled"):
        return

    evaluations = match_info.get("candidate_evaluations", [])
    for evaluation in evaluations:
        candidate_box = evaluation.get("candidate_box")
        if not candidate_box:
            continue
        crop = crop_frame(frame, candidate_box)
        if crop.size == 0:
            continue

        interpolation = cv2.INTER_AREA if crop.shape[0] > DATASET_CROP_SIZE or crop.shape[1] > DATASET_CROP_SIZE else cv2.INTER_LINEAR
        resized = cv2.resize(crop, (DATASET_CROP_SIZE, DATASET_CROP_SIZE), interpolation=interpolation)

        dataset_exporter["counter"] += 1
        label_dir = dataset_exporter["float_dir"] if evaluation["accepted"] else dataset_exporter["non_float_dir"]
        template_id = evaluation.get("template_id") or "none"
        filename = (
            f"{source_label}_f{frame_index:06d}_c{evaluation['candidate_index']:02d}_"
            f"n{dataset_exporter['counter']:07d}_{template_id}_"
            f"s{evaluation['score']:.4f}_t{evaluation['threshold']:.4f}.png"
        )
        cv2.imwrite(str(label_dir / filename), resized)

def update_tracking_state(state: dict, match_info: dict, args: argparse.Namespace, frame_index: int) -> dict:
    score = match_info["score"]
    target_rect = match_info["target_rect"]
    tracking_threshold = match_info["tracking_threshold"]
    locked_before = state["locked"]
    bite_before = state["bite_event"]
    valid_detection = score >= tracking_threshold and match_info["search_source"] in ("candidate", "local", "global")

    if score >= tracking_threshold:
        state["locked"] = True
        state["tracked_rect"] = target_rect
        state["lost_frames"] = 0
        if state["active_template_id"] != match_info["template_id"]:
            if state["active_template_id"] is not None:
                state["template_switches"] += 1
            state["active_template_id"] = match_info["template_id"]
        state["template_miss_frames"] = 0
    else:
        state["lost_frames"] += 1
        state["template_miss_frames"] += 1
        if state["lost_frames"] >= args.reacquire_frames:
            state["locked"] = False
            state["tracked_rect"] = None

    if valid_detection:
        point = {
            "frame_index": frame_index,
            "center_x": target_rect["center_x"],
            "center_y": target_rect["center_y"],
            "score": score,
            "best_mode": match_info["best_mode"],
            "search_source": match_info["search_source"],
            "locked": state["locked"],
            "template_id": match_info["template_id"],
        }
        state["history"].append(point)
        if len(state["history"]) > args.history_size:
            state["history"].popleft()

    bite = detect_bite_event(state["history"], match_info["tracking_threshold"], args, state["locked"])
    state["bite_event"] = bite["triggered"]
    state["bite_metrics"] = bite
    state["just_locked"] = state["locked"] and not locked_before
    state["just_bite_event"] = state["bite_event"] and not bite_before
    state["valid_detection"] = valid_detection
    return state


def detect_bite_event(history: deque, tracking_threshold: float, args: argparse.Namespace, is_locked: bool) -> dict:
    if not is_locked or len(history) < args.bite_window:
        return {"triggered": False, "drop_pixels": 0.0, "speed": 0.0}

    recent = list(history)[-args.bite_window :]
    if any(item["score"] < tracking_threshold for item in recent):
        return {"triggered": False, "drop_pixels": 0.0, "speed": 0.0}

    start = recent[0]
    end = recent[-1]
    drop_pixels = end["center_y"] - start["center_y"]
    frame_span = max(1, end["frame_index"] - start["frame_index"])
    speed = drop_pixels / frame_span

    stable_prefix = recent[:-2]
    if stable_prefix:
        ys = [item["center_y"] for item in stable_prefix]
        prefix_range = max(ys) - min(ys)
    else:
        prefix_range = 0.0

    triggered = drop_pixels >= args.bite_drop_pixels and prefix_range <= args.bite_drop_pixels * 0.6 and speed > 1.5
    return {"triggered": triggered, "drop_pixels": drop_pixels, "speed": speed}


def draw_tracking_path(frame, history: deque) -> None:
    points = [(int(round(item["center_x"])), int(round(item["center_y"]))) for item in history]
    if len(points) < 2:
        return
    for idx in range(1, len(points)):
        intensity = 80 + int(175 * idx / max(1, len(points) - 1))
        cv2.line(frame, points[idx - 1], points[idx], (0, intensity, 255), 2, cv2.LINE_AA)
    for point in points[-3:]:
        cv2.circle(frame, point, 3, (255, 255, 255), -1, cv2.LINE_AA)


def draw_overlay(frame, score: float, target_rect: dict, threshold: float, current_fps: float, best_mode: str, tracking_state: dict):
    output = frame.copy()
    hit = score >= threshold
    locked = tracking_state["locked"]
    bite_event = tracking_state["bite_event"]
    color = (0, 255, 255) if locked else ((0, 200, 0) if hit else (0, 0, 255))
    if bite_event:
        color = (0, 165, 255)

    top_left = (int(target_rect["left"]), int(target_rect["top"]))
    bottom_right = (int(target_rect["right"]), int(target_rect["bottom"]))
    cv2.rectangle(output, top_left, bottom_right, color, 2)

    search_region = tracking_state.get("active_search_region")
    if search_region is not None:
        search_top_left = (int(search_region["left"]), int(search_region["top"]))
        search_bottom_right = (
            int(search_region["left"] + search_region["width"]),
            int(search_region["top"] + search_region["height"]),
        )
        cv2.rectangle(output, search_top_left, search_bottom_right, (255, 255, 0), 1)

    for candidate in tracking_state.get("candidate_boxes", []):
        c_top_left = (int(candidate["left"]), int(candidate["top"]))
        c_bottom_right = (int(candidate["left"] + candidate["width"]), int(candidate["top"] + candidate["height"]))
        cv2.rectangle(output, c_top_left, c_bottom_right, (120, 255, 120), 1)

    draw_tracking_path(output, tracking_state["history"])

    bite_metrics = tracking_state["bite_metrics"]
    candidate_debug = tracking_state.get("candidate_debug", {})
    lines = [
        f"Score: {score:.4f} ({score * 100:.2f}%) | Template: {tracking_state['active_template_id'] or 'none'}",
        (
            f"Threshold: {threshold:.2f} | Track: {tracking_state['active_tracking_threshold']:.2f} | "
            f"Lock: {'ON' if locked else 'OFF'} | Mode: {best_mode}"
        ),
        (
            f"FPS: {current_fps:.2f} | Search: {tracking_state['search_source']} | "
            f"Valid: {'YES' if tracking_state['valid_detection'] else 'NO'} | Switches: {tracking_state['template_switches']}"
        ),
        (
            f"Mask: {tracking_state['candidate_mask_mode']} | HaloGate: {'ON' if tracking_state['halo_gate_enabled'] else 'OFF'} | "
            f"Candidates: {candidate_debug.get('gated_candidates', 0)}/{candidate_debug.get('raw_candidates', 0)}"
        ),
        (
            "DropWindow: "
            f"{bite_metrics['drop_pixels']:.1f}px | Speed: {bite_metrics['speed']:.2f}px/frame | "
            f"BITE: {'YES' if bite_event else 'NO'}"
        ),
        (
            f"Sound: {tracking_state['sound_level']:.1f}/{tracking_state['sound_threshold']:.1f} | "
            f"Monitor: {'ON' if tracking_state['sound_monitor_enabled'] else 'OFF'} | "
            f"State: {'TRIGGER' if tracking_state['sound_level'] > tracking_state['sound_threshold'] else 'IDLE'}"
        ),
        f"Fail: {tracking_state['failure_reason'] or 'none'} | MatchTemplate: {tracking_state['match_template_id'] or 'none'}",
    ]

    y = 25
    for line in lines:
        cv2.putText(output, line, (10, y), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color if y < 60 else (255, 255, 255), 2, cv2.LINE_AA)
        y += 26

    if tracking_state.get("sound_notification_text") and tracking_state.get("sound_notification_until", 0.0) > time.monotonic():
        notice = tracking_state["sound_notification_text"]
        notice_top = max(10, output.shape[0] - 58)
        cv2.rectangle(output, (10, notice_top), (min(output.shape[1] - 10, 760), notice_top + 38), (0, 140, 255), -1)
        cv2.putText(output, notice, (18, notice_top + 26), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2, cv2.LINE_AA)

    return output


def resize_to_height(image, target_height: int):
    if image.ndim == 2:
        image = cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)
    if image.shape[0] == target_height:
        return image
    scale = target_height / image.shape[0]
    target_width = max(1, int(round(image.shape[1] * scale)))
    return cv2.resize(image, (target_width, target_height), interpolation=cv2.INTER_AREA)


def build_match_dashboard(frame, matched_overlay, result_map, match_info: dict, tracking_state: dict):
    panel_height = 220
    frame_panel = resize_to_height(frame, panel_height)
    template_panel = resize_to_height(match_info["template_image"], panel_height)
    overlay_panel = resize_to_height(matched_overlay, panel_height)
    normalized = cv2.normalize(result_map, None, 0, 255, cv2.NORM_MINMAX)
    heatmap = cv2.applyColorMap(normalized.astype(np.uint8), cv2.COLORMAP_JET)
    heatmap_panel = resize_to_height(heatmap, panel_height)
    processed_capture_panel = resize_to_height(prepare_variant(frame, match_info["best_mode"]), panel_height)
    processed_template_panel = resize_to_height(prepare_variant(match_info["template_image"], match_info["best_mode"]), panel_height)
    float_mask_panel = resize_to_height(match_info["float_mask"], panel_height)

    separator = np.full((panel_height, 12, 3), 30, dtype=np.uint8)
    dashboard = np.hstack(
        [
            frame_panel,
            separator,
            processed_capture_panel,
            separator,
            processed_template_panel,
            separator,
            float_mask_panel,
            separator,
            template_panel,
            separator,
            overlay_panel,
            separator,
            heatmap_panel,
        ]
    )

    panel_widths = [
        frame_panel.shape[1],
        processed_capture_panel.shape[1],
        processed_template_panel.shape[1],
        float_mask_panel.shape[1],
        template_panel.shape[1],
        overlay_panel.shape[1],
        heatmap_panel.shape[1],
    ]
    labels = [
        "Capture",
        "Processed Capture",
        "Processed Template",
        "Float Mask",
        f"Template: {match_info['template_id']}",
        "Tracked Overlay",
        "Heatmap",
    ]
    x = 10
    for width, label in zip(panel_widths, labels):
        cv2.putText(dashboard, label, (x, 25), cv2.FONT_HERSHEY_SIMPLEX, 0.75, (255, 255, 255), 2, cv2.LINE_AA)
        x += width + 12

    score_text = " | ".join(f"{name}={value:.4f}" for name, value in match_info["scores"].items())
    template_score_entries = match_info.get("template_scores", [])
    template_score_text = " | ".join(
        f"{entry['template_id']}={entry['score']:.4f}" for entry in template_score_entries[:6]
    )
    if len(template_score_entries) > 6:
        template_score_text += f" | +{len(template_score_entries) - 6} more"
    bite_metrics = tracking_state["bite_metrics"]
    candidate_debug = tracking_state.get("candidate_debug", {})
    footer_lines = [
        (
            f"Similarity: {match_info['score']:.4f} ({match_info['score'] * 100:.2f}%) | "
            f"Best: {match_info['best_mode']} | Template: {match_info['template_id']}"
        ),
        f"Scores: {score_text}",
        f"Template Scores: {template_score_text or 'n/a'}",
        (
            f"Lock={'ON' if tracking_state['locked'] else 'OFF'} | "
            f"LostFrames={tracking_state['lost_frames']} | TemplateMiss={tracking_state['template_miss_frames']} | "
            f"Switches={tracking_state['template_switches']} | Source={tracking_state['search_source']} | "
            f"Fail={tracking_state['failure_reason'] or 'none'}"
        ),
        (
            f"Mask={tracking_state['candidate_mask_mode']} | HaloGate={'ON' if tracking_state['halo_gate_enabled'] else 'OFF'} | "
            f"Candidates={candidate_debug.get('gated_candidates', 0)}/{candidate_debug.get('raw_candidates', 0)} | "
            f"RejectedHalo={candidate_debug.get('rejected_by_halo', 0)} | "
            f"Drop={bite_metrics['drop_pixels']:.1f}px | Speed={bite_metrics['speed']:.2f}px/frame | "
            f"Bite={'YES' if tracking_state['bite_event'] else 'NO'}"
        ),
        (
            f"Sound={tracking_state['sound_level']:.1f}/{tracking_state['sound_threshold']:.1f} | "
            f"Monitor={'ON' if tracking_state['sound_monitor_enabled'] else 'OFF'} | "
            f"State={'TRIGGER' if tracking_state['sound_level'] > tracking_state['sound_threshold'] else 'IDLE'} | "
            f"AudioError={tracking_state['sound_device_error'] or 'none'}"
        ),
    ]
    if tracking_state.get("sound_notification_text") and tracking_state.get("sound_notification_until", 0.0) > time.monotonic():
        footer_lines.append(f"Notification: {tracking_state['sound_notification_text']}")
    y = panel_height - 118
    for line in footer_lines:
        cv2.putText(dashboard, line, (10, y), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (255, 255, 255), 2, cv2.LINE_AA)
        y += 24
    return dashboard


def should_exit_from_preview() -> bool:
    key = cv2.waitKey(1) & 0xFF
    return key in (27, ord("q"))


def announce_bite_event(match_info: dict, tracking_state: dict, frame_index: int, source_label: str) -> None:
    if not tracking_state.get("just_bite_event"):
        return

    bite_metrics = tracking_state["bite_metrics"]
    target_rect = match_info["target_rect"]
    timestamp = time.strftime("%H:%M:%S")
    print(
        f"[{timestamp}] BITE EVENT [{source_label}] frame={frame_index} "
        f"template={match_info['template_id']} score={match_info['score']:.4f} "
        f"drop={bite_metrics['drop_pixels']:.1f}px speed={bite_metrics['speed']:.2f}px/frame "
        f"center=({target_rect['center_x']:.1f},{target_rect['center_y']:.1f})",
        flush=True,
    )


def initialize_tracking_state(args: argparse.Namespace) -> dict:
    return {
        "locked": False,
        "tracked_rect": None,
        "lost_frames": 0,
        "history": deque(maxlen=args.history_size),
        "bite_event": False,
        "bite_metrics": {"triggered": False, "drop_pixels": 0.0, "speed": 0.0},
        "search_source": "global",
        "active_search_region": None,
        "candidate_boxes": [],
        "candidate_debug": {},
        "failure_reason": None,
        "valid_detection": False,
        "just_locked": False,
        "just_bite_event": False,
        "active_template_id": None,
        "match_template_id": None,
        "template_switches": 0,
        "template_miss_frames": DEFAULT_TEMPLATE_SWITCH_FRAMES,
        "active_tracking_threshold": args.tracking_threshold,
        "candidate_mask_mode": args.candidate_mask_mode,
        "halo_gate_enabled": args.use_halo_gate,
        "sound_notification_text": None,
        "sound_notification_until": 0.0,
        "sound_level": 0.0,
        "sound_threshold": float(args.sound_threshold),
        "sound_monitor_enabled": bool(args.enable_sound_monitor),
        "sound_device_error": None,
    }


def allow_template_switch(tracking_state: dict) -> bool:
    return (not tracking_state["locked"]) or tracking_state["template_miss_frames"] >= DEFAULT_TEMPLATE_SWITCH_FRAMES


def record_match_state(tracking_state: dict, match_info: dict) -> None:
    tracking_state["search_source"] = match_info["search_source"]
    tracking_state["active_search_region"] = match_info["search_region"]
    tracking_state["candidate_boxes"] = match_info.get("candidate_boxes", [])
    tracking_state["candidate_debug"] = match_info.get("candidate_debug", {})
    tracking_state["failure_reason"] = match_info.get("failure_reason")
    tracking_state["match_template_id"] = match_info.get("template_id")
    tracking_state["active_tracking_threshold"] = match_info.get("tracking_threshold", tracking_state["active_tracking_threshold"])
    tracking_state["candidate_mask_mode"] = match_info.get("candidate_mask_mode", tracking_state["candidate_mask_mode"])
    tracking_state["halo_gate_enabled"] = match_info.get("halo_gate_enabled", tracking_state["halo_gate_enabled"])


def format_status_line(match_info: dict, tracking_state: dict) -> str:
    status = "BITE" if tracking_state["bite_event"] else ("TRACKED" if tracking_state["locked"] else "SEARCH")
    timestamp = time.strftime("%H:%M:%S")
    candidate_debug = tracking_state.get("candidate_debug", {})
    return (
        f"[{timestamp}] similarity={match_info['score']:.4f} status={status} mode={match_info['best_mode']} "
        f"template={match_info['template_id']} search={tracking_state['search_source']} "
        f"valid={tracking_state['valid_detection']} candidates={candidate_debug.get('gated_candidates', 0)}/"
        f"{candidate_debug.get('raw_candidates', 0)} halo-gate={'on' if tracking_state['halo_gate_enabled'] else 'off'} "
        f"sound={tracking_state['sound_level']:.1f}/{tracking_state['sound_threshold']:.1f} "
        f"fail={tracking_state['failure_reason'] or 'none'} center=({match_info['target_rect']['center_x']:.1f},"
        f"{match_info['target_rect']['center_y']:.1f}) drop={tracking_state['bite_metrics']['drop_pixels']:.1f}"
    )


def resolve_replay_region(args: argparse.Namespace, frame_shape) -> dict:
    frame_height, frame_width = frame_shape[:2]
    monitor = {"left": 0, "top": 0, "width": frame_width, "height": frame_height}
    if args.region_width is None or args.region_height is None:
        return {"left": 0, "top": 0, "width": frame_width, "height": frame_height}
    region = resolve_region(args, monitor)
    validate_region(region, monitor)
    return region


def list_replay_frames(replay_dir: Path) -> list[Path]:
    frames = [path for path in sorted(replay_dir.iterdir()) if path.is_file() and path.suffix.lower() in SUPPORTED_IMAGE_SUFFIXES]
    if not frames:
        raise ValueError(f"no supported replay frames found in: {replay_dir}")
    return frames


def serialize_replay_row(frame_path: Path, frame_index: int, match_info: dict, tracking_state: dict) -> dict:
    candidate_debug = tracking_state.get("candidate_debug", {})
    return {
        "frame_index": frame_index,
        "frame": frame_path.name,
        "template_id": match_info["template_id"],
        "score": round(float(match_info["score"]), 6),
        "best_mode": match_info["best_mode"],
        "search_source": tracking_state["search_source"],
        "valid_detection": tracking_state["valid_detection"],
        "locked": tracking_state["locked"],
        "bite_event": tracking_state["bite_event"],
        "candidate_count": candidate_debug.get("gated_candidates", 0),
        "candidate_raw_count": candidate_debug.get("raw_candidates", 0),
        "failure_reason": tracking_state["failure_reason"],
        "center_x": round(float(match_info["target_rect"]["center_x"]), 2),
        "center_y": round(float(match_info["target_rect"]["center_y"]), 2),
    }


def write_replay_output(output_path: Path, rows: list[dict]) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.suffix.lower() == ".json":
        output_path.write_text(json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8")
        return

    fieldnames = list(rows[0].keys()) if rows else []
    with output_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def build_sound_monitor_state(args: argparse.Namespace) -> dict:
    return {
        "enabled": bool(args.enable_sound_monitor),
        "threshold": float(args.sound_threshold),
        "notification_duration": float(args.sound_notification_duration),
        "current_level": 0.0,
        "notification_text": None,
        "notification_until": 0.0,
        "warning_printed": False,
        "device_error": None,
        "lock": threading.Lock(),
        "stop_event": threading.Event(),
        "thread": None,
    }


def trigger_sound_notification(sound_monitor: dict, text: str) -> None:
    now = time.monotonic()
    with sound_monitor["lock"]:
        sound_monitor["notification_text"] = text
        sound_monitor["notification_until"] = now + sound_monitor["notification_duration"]


def sound_monitor_loop(sound_monitor: dict) -> None:
    if sd is None:
        return

    def audio_callback(indata, frames, time_info, status):
        volume_norm = float(np.linalg.norm(indata) * 10)
        with sound_monitor["lock"]:
            sound_monitor["current_level"] = volume_norm
        if volume_norm > sound_monitor["threshold"]:
            trigger_sound_notification(
                sound_monitor,
                f"Sound Trigger: {volume_norm:.1f} > {sound_monitor['threshold']:.1f}",
            )

    stop_event = sound_monitor["stop_event"]
    while not stop_event.is_set():
        try:
            with sd.InputStream(callback=audio_callback):
                while not stop_event.is_set():
                    sd.sleep(200)
        except Exception as exc:
            sound_monitor["device_error"] = str(exc)
            if not sound_monitor["warning_printed"]:
                print(f"Sound monitor disabled: {exc}", flush=True)
                sound_monitor["warning_printed"] = True
            trigger_sound_notification(sound_monitor, "Sound Monitor Error")
            return


def start_sound_monitor(sound_monitor: dict) -> None:
    if not sound_monitor["enabled"]:
        return
    if sd is None:
        if not sound_monitor["warning_printed"]:
            print("Sound monitor unavailable: sounddevice is not installed.", flush=True)
            sound_monitor["warning_printed"] = True
        sound_monitor["enabled"] = False
        return
    thread = threading.Thread(target=sound_monitor_loop, args=(sound_monitor,), daemon=True)
    sound_monitor["thread"] = thread
    thread.start()


def stop_sound_monitor(sound_monitor: dict) -> None:
    sound_monitor["stop_event"].set()
    thread = sound_monitor.get("thread")
    if thread is not None and thread.is_alive():
        thread.join(timeout=1.0)


def refresh_sound_notification(tracking_state: dict, sound_monitor: dict) -> None:
    now = time.monotonic()
    with sound_monitor["lock"]:
        level = float(sound_monitor.get("current_level", 0.0))
        text = sound_monitor["notification_text"]
        until = sound_monitor["notification_until"]
        device_error = sound_monitor.get("device_error")
        enabled = bool(sound_monitor.get("enabled"))
        threshold = float(sound_monitor.get("threshold", tracking_state["sound_threshold"]))

    tracking_state["sound_level"] = level
    tracking_state["sound_threshold"] = threshold
    tracking_state["sound_monitor_enabled"] = enabled
    tracking_state["sound_device_error"] = device_error

    if text and until > now:
        tracking_state["sound_notification_text"] = text
        tracking_state["sound_notification_until"] = until
    elif tracking_state.get("sound_notification_until", 0.0) <= now:
        tracking_state["sound_notification_text"] = None
        tracking_state["sound_notification_until"] = 0.0


def run_live_capture(args: argparse.Namespace, template_entries: list[dict], source_note: str) -> int:
    with mss.mss() as sct:
        monitor = get_primary_monitor(sct)
        region = resolve_region(args, monitor)
        validate_region(region, monitor)
        ensure_templates_fit(region, template_entries)

        interval = 1.0 / args.fps
        next_capture_at = time.perf_counter()
        last_loop_at = None
        tracking_state = initialize_tracking_state(args)
        dataset_exporter = build_candidate_dataset_exporter(args)
        sound_monitor = build_sound_monitor_state(args)
        start_sound_monitor(sound_monitor)

        print(
            "Starting capture with "
            f"{source_note}, templates={len(template_entries)}, region={region['width']}x{region['height']} "
            f"at ({region['left']}, {region['top']}), fps={args.fps:.2f}, "
            f"threshold={args.threshold:.2f}, default-tracking-threshold={args.tracking_threshold:.2f}, "
            f"candidate-mask={args.candidate_mask_mode}, halo-gate={'on' if args.use_halo_gate else 'off'}, "
            f"max-candidates={args.max_candidates}, "
            f"dataset-export={'on' if dataset_exporter['enabled'] else 'off'}, "
            f"sound-monitor={'on' if sound_monitor['enabled'] else 'off'}, "
            f"preview={'on' if args.show_preview else 'off'}"
        )
        print(f"Loaded templates: {describe_template_entries(template_entries)}", flush=True)
        if dataset_exporter["enabled"]:
            print(
                f"Candidate dataset export enabled: float={dataset_exporter['float_dir']} "
                f"non_float={dataset_exporter['non_float_dir']}",
                flush=True,
            )

        frame_index = 0
        try:
            while True:
                refresh_sound_notification(tracking_state, sound_monitor)
                now = time.perf_counter()
                remaining = next_capture_at - now
                if remaining > 0:
                    time.sleep(min(remaining, 0.01))
                    continue

                frame = capture_region(sct, region)
                match_info = detect_target(
                    frame=frame,
                    template_entries=template_entries,
                    match_mode=args.match_mode,
                    tracked_rect=tracking_state["tracked_rect"] if tracking_state["locked"] else None,
                    search_padding=args.search_padding,
                    use_halo_gate=args.use_halo_gate,
                    candidate_mask_mode=args.candidate_mask_mode,
                    candidate_min_area=args.candidate_min_area,
                    max_candidates=args.max_candidates,
                    active_template_id=tracking_state["active_template_id"],
                    allow_template_switch=allow_template_switch(tracking_state),
                )
                save_candidate_dataset_samples(frame, match_info, dataset_exporter, frame_index, "live")
                record_match_state(tracking_state, match_info)
                update_tracking_state(tracking_state, match_info, args, frame_index)
                announce_bite_event(match_info, tracking_state, frame_index, "live")

                loop_now = time.perf_counter()
                current_fps = 0.0 if last_loop_at is None else 1.0 / max(loop_now - last_loop_at, 1e-6)
                last_loop_at = loop_now

                print(format_status_line(match_info, tracking_state), flush=True)

                if args.show_preview:
                    capture_preview = draw_overlay(
                        frame=frame,
                        score=match_info["score"],
                        target_rect=match_info["target_rect"],
                        threshold=args.threshold,
                        current_fps=current_fps,
                        best_mode=match_info["best_mode"],
                        tracking_state=tracking_state,
                    )
                    dashboard = build_match_dashboard(
                        frame=frame,
                        matched_overlay=capture_preview,
                        result_map=match_info["result_map"],
                        match_info=match_info,
                        tracking_state=tracking_state,
                    )
                    cv2.imshow(WINDOW_NAME_CAPTURE, capture_preview)
                    cv2.imshow(WINDOW_NAME_DASHBOARD, dashboard)
                    if should_exit_from_preview():
                        break
                    if cv2.getWindowProperty(WINDOW_NAME_CAPTURE, cv2.WND_PROP_VISIBLE) < 1:
                        break
                    if cv2.getWindowProperty(WINDOW_NAME_DASHBOARD, cv2.WND_PROP_VISIBLE) < 1:
                        break

                next_capture_at = max(next_capture_at + interval, time.perf_counter())
                frame_index += 1
        finally:
            stop_sound_monitor(sound_monitor)
            if args.show_preview:
                cv2.destroyAllWindows()

    return 0


def run_replay(args: argparse.Namespace, template_entries: list[dict], source_note: str) -> int:
    replay_dir = Path(args.replay_dir).expanduser().resolve()
    frame_paths = list_replay_frames(replay_dir)
    tracking_state = initialize_tracking_state(args)
    dataset_exporter = build_candidate_dataset_exporter(args)
    rows = []

    first_frame = load_image_file(frame_paths[0])
    region = resolve_replay_region(args, first_frame.shape)
    ensure_templates_fit(region, template_entries)

    print(
        "Starting replay with "
        f"{source_note}, templates={len(template_entries)}, frames={len(frame_paths)}, "
        f"region={region['width']}x{region['height']} at ({region['left']}, {region['top']}), "
        f"dataset-export={'on' if dataset_exporter['enabled'] else 'off'}"
    )
    print(f"Loaded templates: {describe_template_entries(template_entries)}", flush=True)
    if dataset_exporter["enabled"]:
        print(
            f"Candidate dataset export enabled: float={dataset_exporter['float_dir']} "
            f"non_float={dataset_exporter['non_float_dir']}",
            flush=True,
        )

    for frame_index, frame_path in enumerate(frame_paths):
        full_frame = load_image_file(frame_path)
        cropped_frame = crop_frame(full_frame, region)
        match_info = detect_target(
            frame=cropped_frame,
            template_entries=template_entries,
            match_mode=args.match_mode,
            tracked_rect=tracking_state["tracked_rect"] if tracking_state["locked"] else None,
            search_padding=args.search_padding,
            use_halo_gate=args.use_halo_gate,
            candidate_mask_mode=args.candidate_mask_mode,
            candidate_min_area=args.candidate_min_area,
            max_candidates=args.max_candidates,
            active_template_id=tracking_state["active_template_id"],
            allow_template_switch=allow_template_switch(tracking_state),
        )
        save_candidate_dataset_samples(cropped_frame, match_info, dataset_exporter, frame_index, "replay")
        record_match_state(tracking_state, match_info)
        update_tracking_state(tracking_state, match_info, args, frame_index)
        announce_bite_event(match_info, tracking_state, frame_index, "replay")
        row = serialize_replay_row(frame_path, frame_index, match_info, tracking_state)
        rows.append(row)
        print(
            f"[{frame_index:04d}] frame={frame_path.name} score={match_info['score']:.4f} "
            f"template={match_info['template_id']} source={tracking_state['search_source']} "
            f"lock={tracking_state['locked']} bite={tracking_state['bite_event']}"
        )

    if args.replay_output:
        output_path = Path(args.replay_output).expanduser().resolve()
        write_replay_output(output_path, rows)
        print(f"Replay results written to: {output_path}")

    return 0


def run(args: argparse.Namespace) -> int:
    ensure_dependencies_loaded()
    args = apply_config_defaults(args)
    args = prepare_path_arguments(args)
    validate_args(args)
    template_entries, source_note = load_templates(args)

    if args.replay_dir:
        return run_replay(args, template_entries, source_note)
    return run_live_capture(args, template_entries, source_note)


def main() -> int:
    try:
        return run(parse_args())
    except KeyboardInterrupt:
        print("Interrupted by user.")
        return 130
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
